asw_lidar_node:
  ros__parameters:
    Task1.voxel_size: 0.08
    Task1.min_x_: 0
    Task1.max_x_: 2.0
    Task1.min_y_: -0.6
    Task1.max_y_: 0.6
    Task1.tolerance: 0.1
    Task1.cluster_size_min: 1
    Task1.cluster_size_max: 50
    Task1.cone_dist: 0.3
    Task1.dist_offset: 0.8
    Task2.voxel_size: 0.1
    Task2.min_x_: 0.0
    Task2.max_x_: 5.0
    Task2.min_y_: -2.0
    Task2.max_y_: 2.0
    Task2.cone_dist_: 0.2
    Task2.chan_dist_offset: 0.35
    Task2.dist_offset: 1.3
    Task2.outcourse_offset: 0.0
    Task2.straight_count_param: 18
    Task2.straight_angle: -8
    Task2.ratio_line: 0.15
    Task2.ratio_line2: 0.35
    Task2.done_count_param: 5
    Task2.corner_speed: 0.3
    Task2.LD: 0.5
    Task3.voxel_size: 0.03
    Task3.min_x_: 0.13
    Task3.max_x_: 0.65
    Task3.min_y_: -0.1
    Task3.max_y_: 0.1
    Task3.tolerance: 0.2
    Task3.cluster_size_min: 4
    Task3.cluster_size_max: 500
    Task4.voxel_size: 0.01
    Task4.min_x_: 0.0
    Task4.max_x_: 0.8
    Task4.min_y_: -0.2
    Task4.max_y_: 0.2
    Task4.tolerance: 0.3
    Task4.cluster_size_min: 2
    Task4.cluster_size_max: 500
    Task5.voxel_size: 0.06
    Task5.min_x_: 0.0
    Task5.max_x_: 2.0
    Task5.min_y_: -0.5
    Task5.max_y_: 0.5
    Task5.cone_dist_: 0.2
    Task5.chan_dist_offset: 0.35
    Task5.dist_offset: 1.3
    Task5.outcourse_offset: 0.0
    Task5.straight_count_param: 18
    Task5.straight_angle: -8
    Task5.ratio_line: 0.15
    Task5.ratio_line2: 0.35
    Task5.done_count_param: 5
    Task5.corner_speed: 0.2
    Task5.LD: 0.5
    Task6.voxel_size: 0.01
    Task6.min_x_: 0.0
    Task6.max_x_: 1.8
    Task6.min_y_: -0.2
    Task6.max_y_: 0.2
    Task6.tolerance: 0.3
    Task6.cluster_size_min: 2
    Task6.cluster_size_max: 500
    track.voxel_size: 0.08
    track.min_x_: 0
    track.max_x_: 2.0
    track.min_y_: -0.6
    track.max_y_: 0.6
    track.tolerance: 0.1
    track.cluster_size_min: 1
    track.cluster_size_max: 50
    track.cone_dist: 0.3
    track.dist_offset: 0.8
    track.done_count_param: 5
    track.done_size: 5
    parent.frame_id: laser
    state.Task1_state: 24
    state.Task2_state: 25
    state.Task3_state: 26
    state.Task4_state: 27
    state.Task5_state: 28
    state.Task6_state: 29
